image: node:lts-buster

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/
  key: "$CI_BUILD_REPO" 

before_script:
  - npm i -g firebase-tools

deploy-functions-develop:
  stage: deploy
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase use display-it-dev --token $FIREBASE_TOKEN_DEVELOP
    - firebase deploy --only functions -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN_DEVELOP
  only:
    refs:
      - develop
    changes:
      - functions/**/*

deploy-vuejs-develop:
  stage: deploy
  only:
    refs:
      - develop
    changes:
      - src/**/*
      - package*.json
  script:
    - npm install
    - VUE_APP_PROD_CONFIG=no npm run build
    - firebase use display-it-dev --token $FIREBASE_TOKEN_DEVELOP
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN_DEVELOP

deploy-functions-production:
  stage: deploy
  script:
    - cd functions
    - npm install
    - cd ..
    - firebase use display-it --token $FIREBASE_TOKEN_PRODUCTION
    - firebase deploy --only functions -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN_PRODUCTION
  only:
    refs:
      - master
    changes:
      - functions/**/*

deploy-vuejs-production:
  stage: deploy
  only:
    refs:
      - master
    changes:
      - src/**/*
      - package*.json
  script:
    - npm install
    - VUE_APP_PROD_CONFIG=yes npm run build
    - firebase use display-it --token $FIREBASE_TOKEN_PRODUCTION
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token $FIREBASE_TOKEN_PRODUCTION
